% build_and_run_eeg_udp.m
% Receive 40-ch EEG @100 Hz over UDP on a Speedgoat target, display channel 1

%% 0) Cleanup
close all; clear variables; clc;

%% 1) Connect to Speedgoat target (host ↔ 192.168.7.5)
tg = slrealtime('192.168.7.5');
tg.connect;

%% 2) Alias ETH1 so it receives from your EEG sender
IP_SENDER = '192.168.200.220';   % EEG system
IP_TARGET = '192.168.200.240';   % Speedgoat ETH1
ipCfg = speedgoat.IpAliasConfiguration('TargetObject', tg);
ipCfg.add('ETH1', {IP_SENDER, IP_TARGET});
ipCfg.show;

%% 3) Load the Real-Time IP library
load_system('slrealtimeiplib');

%% 4) Create & open new Simulink model
modelName = 'EEG_UDP_RTModel';
if bdIsLoaded(modelName), close_system(modelName,0); end
new_system(modelName);
open_system(modelName);

%% 5) Add & configure UDP Receiver
udpBlk = add_block(...
    'slrealtimeiplib/UDP Receive',...
    [modelName '/UDP Receiver'],...
    'Position',[30 30 180 80]...
);
set_param(udpBlk,...
  'ipAddress',   IP_SENDER,...   % accept only from EEG source
  'localPort',   '5000',...      % UDP port
  'sampleTime',  '0.01',...      % 100 Hz
  'rcvWidth',    '400',...       % 40 ch × 10 samples
  'rcvFmAny',    'off',...
  'fmAddress',   IP_SENDER,...
  'maxPackets',  '1'...
);

%% 6) Convert to double
dtcBlk = add_block(...
    'simulink/Signal Attributes/Data Type Conversion',...
    [modelName '/ConvertToDouble'],...
    'Position',[240 30 350 80],...
    'OutDataTypeStr','double'...
);
add_line(modelName,'UDP Receiver/1','ConvertToDouble/1');

%% 7) Reshape to 400×1
reshapeBlk = add_block(...
    'simulink/Math Operations/Reshape',...
    [modelName '/Reshape'],...
    'Position',[380 30 520 80]...
);
set_param(reshapeBlk,'OutputDimensions','[400,1]');
add_line(modelName,'ConvertToDouble/1','Reshape/1');

%% 8) Pick channel 1 via 1-D Selector
selBlk = add_block(...
    'simulink/Signal Routing/Selector',...
    [modelName '/SelectCh1'],...
    'Position',[560 30 620 90]...
);
% configure with a cell-array for IndexParamArray
set_param(selBlk,...
  'IndexMode',       'One-based',...
  'InputPortWidth',  '400',...           % length of the incoming vector
  'IndexParamArray', {'1:40:400'} ...    % elements 1,41,81,… = channel 1
);
add_line(modelName,'Reshape/1','SelectCh1/1');

%% 9) Show channel 1 in a Scope
scopeBlk = add_block(...
    'simulink/Commonly Used Blocks/Scope',...
    [modelName '/Scope_Ch1'],...
    'Position',[660 30 740 90],...
    'NumInputPorts','1'...
);
add_line(modelName,'SelectCh1/1','Scope_Ch1/1');

%% 10) Configure for Speedgoat real-time
set_param(modelName,...
  'SystemTargetFile','speedgoat.tlc',...
  'TemplateMakefile','speedgoat_default_tmf',...
  'Solver','FixedStepDiscrete',...
  'FixedStep','0.01',...   % match 100 Hz
  'StopTime','inf'...
);
save_system(modelName);

%% 11) Build, download & start
slbuild(modelName);    % compile
tg.load(modelName);    % downloa
