close all; clear all;

% build_slrt_eeg_model  Create a Speedgoat Simulink model via MATLAB script
%
% This builds a model that:
%   1) Receives NeurOne UDP packets
%   2) Decodes Samples packets (int24)
%   3) Maintains a 0.5 s rolling buffer per channel
%   4) Computes FFT amplitude + phase between 4–250 Hz
%
% Notes:
% - Assumes Samples packets only (FrameType = 2).
% - Uses fixed NumChannels and NumSampleBundles to keep codegen fixed-size.

%% Parameters (edit as needed)
modelName = 'slrt_eeg_rt';

numChannels = 40;
samplingRateHz = 1000;      % Hz
numSampleBundles = 1;       % samples per UDP packet (delivery rate = 1000 Hz)
windowSec = 0.5;            % rolling buffer length (s)
fLow = 4;                   % Hz
fHigh = 250;                % Hz
fStep = 1;                  % Hz (wavelet frequency resolution)
waveletCycles = 7;          % Morlet wavelet cycles

localIP = '192.168.200.240'; % Speedgoat IP (local interface)
localPort = 50000;            % UDP port for NeurOne packets
receiveFromAny = true;       % receive from any sender
fromIP = '192.168.200.220';  % NeurOne digital out IP (if not receiving from any)

buildAndSave = true;         % create/overwrite model
openModel = false;           % open model after creation

%% Derived parameters
sampleTime = numSampleBundles / samplingRateHz; % packet interval
windowSamples = round(windowSec * samplingRateHz);
if windowSamples < numSampleBundles
    error('windowSec too short: windowSamples < numSampleBundles');
end
payloadLen = 28 + 3*numChannels*numSampleBundles; % Samples packet length (bytes)

freqVec = fLow:fStep:fHigh;
numFreqs = numel(freqVec);
if numFreqs < 1
    error('Invalid frequency bin range. Check fLow/fHigh/fs/nfft.');
end
nfft = 2^nextpow2(windowSamples);

%% Create model
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if buildAndSave && exist([modelName '.slx'], 'file')
    delete([modelName '.slx']);
end
new_system(modelName);
if openModel
    open_system(modelName);
end

%% Add blocks
udpBlock = add_block('slrealtimeiplib/UDP Receive', [modelName '/UDP_Receive']);
set_param(udpBlock, 'ipAddress', localIP);
set_param(udpBlock, 'localPort', num2str(localPort));
set_param(udpBlock, 'rcvWidth', num2str(payloadLen));
set_param(udpBlock, 'rcvFmAny', ternary(receiveFromAny, 'on', 'off'));
set_param(udpBlock, 'fmAddress', fromIP);
set_param(udpBlock, 'sampleTime', num2str(sampleTime));
set_param(udpBlock, 'maxPackets', '1');

decodeBlock = add_block('simulink/User-Defined Functions/MATLAB Function', [modelName '/Decode_Samples']);
bufferBlock = add_block('simulink/User-Defined Functions/MATLAB Function', [modelName '/Update_Buffer']);
specBlock = add_block('simulink/User-Defined Functions/MATLAB Function', [modelName '/Spectral_Analysis']);

ampOut = add_block('simulink/Sinks/Out1', [modelName '/Amp_Out']);
phaseOut = add_block('simulink/Sinks/Out1', [modelName '/Phase_Out']);
freqConst = add_block('simulink/Sources/Constant', [modelName '/Freq_Vector']);
freqOut = add_block('simulink/Sinks/Out1', [modelName '/Freq_Out']);

%% Wire blocks
add_line(modelName, 'UDP_Receive/1', 'Decode_Samples/1');
add_line(modelName, 'UDP_Receive/2', 'Decode_Samples/2');
add_line(modelName, 'Decode_Samples/1', 'Update_Buffer/1');
add_line(modelName, 'Decode_Samples/2', 'Update_Buffer/2');
add_line(modelName, 'Update_Buffer/1', 'Spectral_Analysis/1');
add_line(modelName, 'Update_Buffer/2', 'Spectral_Analysis/2');
add_line(modelName, 'Spectral_Analysis/1', 'Amp_Out/1');
add_line(modelName, 'Spectral_Analysis/2', 'Phase_Out/1');
add_line(modelName, 'Freq_Vector/1', 'Freq_Out/1');

%% Model workspace variables
mw = get_param(modelName, 'ModelWorkspace');
mw.assignin('freqVec', freqVec);
set_param(freqConst, 'Value', 'freqVec');

%% MATLAB Function: Decode_Samples
decodeScript = sprintf([ ...
    "function [samples, valid] = Decode_Samples(u, nbytes)\n" ...
    "%%#codegen\n" ...
    "%% Decode NeurOne Samples packet (FrameType=2)\n" ...
    "samples = zeros(%d, %d, 'int32');\n" ...
    "valid = false;\n" ...
    "expectedLen = %d;\n" ...
    "if nargin > 1\n" ...
    "    if nbytes < expectedLen\n" ...
    "        return;\n" ...
    "    end\n" ...
    "end\n" ...
    "if u(1) ~= uint8(2)\n" ...
    "    return;\n" ...
    "end\n" ...
    "payload = u(29:28+3*%d*%d);\n" ...
    "payload = reshape(payload, 3, []);\n" ...
    "vals = int24_to_int32(payload);\n" ...
    "samples = reshape(vals, %d, %d);\n" ...
    "valid = true;\n" ...
    "end\n" ...
    "\n" ...
    "function vals = int24_to_int32(b)\n" ...
    "%% b: 3xN big-endian bytes\n" ...
    "u = bitshift(uint32(b(1,:)), 16) + bitshift(uint32(b(2,:)), 8) + uint32(b(3,:));\n" ...
    "neg = u >= uint32(2^23);\n" ...
    "u(neg) = u(neg) - uint32(2^24);\n" ...
    "vals = int32(u);\n" ...
    "end\n" ...
    ], numChannels, numSampleBundles, payloadLen, numChannels, numSampleBundles, numChannels, numSampleBundles);
set_matlab_function_script(modelName, 'Decode_Samples', decodeScript);

%% MATLAB Function: Update_Buffer
bufferScript = sprintf([ ...
    "function [buf, ready] = Update_Buffer(samples, valid)\n" ...
    "%%#codegen\n" ...
    "persistent bufInt count;\n" ...
    "if isempty(bufInt)\n" ...
    "    bufInt = zeros(%d, %d, 'int32');\n" ...
    "    count = int32(0);\n" ...
    "end\n" ...
    "ready = false;\n" ...
    "if valid\n" ...
    "    n = size(samples, 2);\n" ...
    "    if n >= %d\n" ...
    "        bufInt = samples(:, end-%d+1:end);\n" ...
    "        count = int32(%d);\n" ...
    "    else\n" ...
    "        bufInt(:, 1:%d-n) = bufInt(:, n+1:%d);\n" ...
    "        bufInt(:, %d-n+1:%d) = samples;\n" ...
    "        count = min(int32(%d), count + int32(n));\n" ...
    "    end\n" ...
    "end\n" ...
    "if count >= %d\n" ...
    "    ready = true;\n" ...
    "end\n" ...
    "buf = bufInt;\n" ...
    "end\n" ...
    ], numChannels, windowSamples, windowSamples, windowSamples, windowSamples, windowSamples, windowSamples, windowSamples, windowSamples, windowSamples, windowSamples);
set_matlab_function_script(modelName, 'Update_Buffer', bufferScript);

%% MATLAB Function: Spectral_Analysis (Morlet wavelet)
specScript = sprintf([ ...
    "function [amp, phase] = Spectral_Analysis(buf, ready)\n" ...
    "%%#codegen\n" ...
    "amp = zeros(%d, %d, 'single');\n" ...
    "phase = zeros(%d, %d, 'single');\n" ...
    "if ~ready\n" ...
    "    return;\n" ...
    "end\n" ...
    "%% Precompute wavelet FFTs (persistent)\n" ...
    "persistent wfftShift nfftLocal;\n" ...
    "if isempty(wfftShift)\n" ...
    "    nfftLocal = %d;\n" ...
    "    t = single(-(%d-1):0) / single(%g); %% align wavelet center to last sample\n" ...
    "    wfftShift = complex(zeros(%d, nfftLocal, 'single'));\n" ...
    "    ii = complex(single(0), single(1));\n" ...
    "    for fi = 1:%d\n" ...
    "        f = single(%g) + single(fi-1)*single(%g);\n" ...
    "        s = single(%g) / (single(2*pi)*f);\n" ...
    "        w = exp(ii*single(2*pi)*f*t) .* exp(-(t.^2)/(single(2)*s^2));\n" ...
    "        w = w / sqrt(sum(abs(w).^2));\n" ...
    "        W = fft(single(w), nfftLocal);\n" ...
    "        %% phase shift to read the last-sample coefficient directly\n" ...
    "        k = single(0:nfftLocal-1);\n" ...
    "        W = W .* exp(ii*single(-2*pi)/single(nfftLocal) * k);\n" ...
    "        wfftShift(fi,:) = W;\n" ...
    "    end\n" ...
    "end\n" ...
    "invN = single(1) / single(nfftLocal);\n" ...
    "x = single(buf);\n" ...
    "for ch = 1:%d\n" ...
    "    x(ch,:) = x(ch,:) - mean(x(ch,:));\n" ...
    "    X = fft(x(ch,:), nfftLocal);\n" ...
    "    c = (wfftShift * X.') * invN;\n" ...
    "    amp(ch,:) = abs(c).';\n" ...
    "    phase(ch,:) = angle(c).';\n" ...
    "end\n" ...
    "end\n" ...
    ], numChannels, numFreqs, numChannels, numFreqs, nfft, windowSamples, samplingRateHz, ...
       numFreqs, numFreqs, fLow, fStep, waveletCycles, numChannels);
set_matlab_function_script(modelName, 'Spectral_Analysis', specScript);

%% Model configuration for Speedgoat
set_param(modelName, 'Solver', 'FixedStepDiscrete');
set_param(modelName, 'FixedStep', num2str(sampleTime));
set_param(modelName, 'StopTime', 'inf');
set_param(modelName, 'SystemTargetFile', 'slrealtime.tlc');
set_param(modelName, 'TemplateMakefile', 'slrealtime_default_tmf');

%% Save model
if buildAndSave
    save_system(modelName);
    fprintf('Model saved: %s.slx\n', modelName);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function set_matlab_function_script(modelName, blockName, scriptText)
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', [modelName '/' blockName]);
if isempty(chart)
    error('Could not find MATLAB Function block: %s', blockName);
end
chart.Script = scriptText;
end

function out = ternary(cond, a, b)
if cond
    out = a;
else
    out = b;
end
end
